# =====================================================================================
# The following is a necessary configuration for the FixIt theme.
# =====================================================================================

# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "Hugo FixIt Demo"
baseURL = "http://example.org/"
# Change the default theme to be use when building the site with Hugo
# theme = "FixIt"

[markup]
  _merge = "shallow"

[outputs]
  _merge = "shallow"

# -------------------------------------------------------------------------------------
# Taxonomies Configuration
# See: https://gohugo.io/content-management/taxonomies/#configure-taxonomies
# -------------------------------------------------------------------------------------

[taxonomies]
  _merge = "shallow"

# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[params]
  # FixIt theme version
  version = "0.3.X" # e.g. "0.2.X", "0.2.15", "v0.2.15" etc.
  # ...
  [params.search]
    enable = true
